//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryAPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryProduct
    {
        public int Id { get; set; }
        public int InventoryId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Discount { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual Product Product { get; set; }
    }
}
